DirectoryStructureApp.Web/Models/ErrorViewModel.cs
namespace DirectoryStructureApp.Web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

DirectoryStructureApp.Web/Controllers/DirectoriesController.cs
using DirectoryStructureApp.BLL.DTOs;
using DirectoryStructureApp.BLL.Interfaces;
using DirectoryStructureApp.Web.Models;
using FluentValidation;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Diagnostics;

namespace DirectoryStructureApp.Web.Controllers;

public class DirectoriesController : Controller
{
    private readonly IDirectoryService _directoryService;
    private readonly IFileSystemService _fileSystemImportService;
    public DirectoriesController(
        IDirectoryService directoryService,
        IFileSystemService fileSystemImportService)
    {
        _directoryService = directoryService;
        _fileSystemImportService = fileSystemImportService;
    }

    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
    public async Task<IActionResult> View(int? directoryId)
    {
        var directories = new List<DirectoryDto>();
        if (directoryId == null)
        {
            var rootDirectories = await _directoryService.GetRootDirectoriesAsync();
            directories.AddRange(rootDirectories);
        }
        else
        {
            var directory = await _directoryService.GetDirectoryByIdAsync((int)directoryId);
            if (directory != null)
            {
                directories.Add(directory);
            }
            else
            {
                return RedirectToAction("View");
            }
        }

        return View(directories);
    }

    [HttpGet]
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public async Task<IActionResult> ConfirmDelete(int directoryId)
    {
        var directory = await _directoryService.GetDirectoryByIdAsync(directoryId);
        if (directory == null)
        {
            return RedirectToAction("View");
        }

        return View(directory);
    }

    [HttpPost]
    public async Task<IActionResult> Delete(int directoryId)
    {
        var directoryToDelete = await _directoryService.GetDirectoryByIdAsync(directoryId);
        if (directoryToDelete == null)
        {
            return View();
        }

        var parentId = directoryToDelete.ParentDirectoryId;
        await _directoryService.DeleteDirectoryAsync(directoryId);
        if (parentId != null)
        {
            return RedirectToAction("View", new { directoryId = parentId });
        }

        return RedirectToAction("View");
    }

    [HttpGet]
    public IActionResult Import()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> ImportPath(string path)
    {
        if (string.IsNullOrWhiteSpace(path))
        {
            return View();
        }

        try
        {
            var importDirectories = _fileSystemImportService.ImportDirectoriesFromPath(path);
            await _directoryService.AddDirectoriesAsync(importDirectories);
            return RedirectToAction("Index");
        }
        catch (DirectoryNotFoundException)
        {
            ModelState.AddModelError("", "Directory has not been found by the path provided or the path provided is not valid.");
            return View("Import");
        }
    }

    [HttpPost]
    public async Task<IActionResult> ImportFile(IFormFile file)
    {
        if (file == null || file.Length == 0)
            return Content("File not selected");

        try
        {
            var importDirectories = await _fileSystemImportService.ImportDirectoriesFromFileAsync(file);
            await _directoryService.AddDirectoriesAsync(importDirectories);
            return RedirectToAction("Index");
        }
        catch (ValidationException ex)
        {
            ModelState.AddModelError("", "Mistake in file deserialization: " + ex.Message);
            return View("Import");
        }
        catch (JsonException ex)
        {
            ModelState.AddModelError("", "Mistake in file deserialization: " + ex.Message);
            return View("Import");
        }
    }


    [HttpPost]
    public async Task<IActionResult> ExportFile(int? directoryId)
    {
        var directories = new List<DirectoryDto>();
        if (directoryId == null)
        {
            var rootDirectories = await _directoryService.GetRootDirectoriesWithAllSubsAsync();
            directories.AddRange(rootDirectories);
        }
        else
        {
            var directory = await _directoryService.GetDirectoryByIdWithAllSubsAsync((int)directoryId);
            if (directory == null)
            {
                return RedirectToAction("Error");
            }
            directories.Add(directory);
        }

        _fileSystemImportService.ExportDirectoriesToFile(directories);

        return RedirectToAction("Index");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

DirectoryStructureApp.Web/Views/Directories/ConfirmDelete.cshtml
@using DirectoryStructureApp.BLL.DTOs;
@model DirectoryDto
@{
    ViewData["Title"] = "Delete Directory";
}

<h2>@ViewData["Title"]</h2>

<form asp-controller="Directories" asp-action="Delete" method="post">
    <div class="form-group">
        <label for="path">Are you sure that you want to delete this directory with all subdirectories?</label>
        <h5>Directory name: <strong>@Model.Name</strong></h5>
    </div>
    <input type="hidden" name="directoryId" value="@Model.Id" />
    <button type="submit" class="btn btn-primary">Delete</button>
</form>

DirectoryStructureApp.Web/Views/Directories/Import.cshtml
@{
    ViewData["Title"] = "Import Directories From File System";
}

<h2>@ViewData["Title"]</h2>

<br>
<form asp-controller="Directories" asp-action="ImportPath" method="post">
    <div class="form-group">
        <label for="path">Path to Import:</label>
        <input type="text" class="form-control" id="path" name="path" required />
    </div>
    <button type="submit" class="btn btn-primary">Import Path</button>
</form>
<br>
<form asp-controller="Directories" asp-action="ImportFile" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="file">Choose JSON file to upload:</label>
        <input type="file" id="file" name="file" accept=".json" required />
    </div>
    <button type="submit" class="btn btn-primary">Upload</button>
</form>
<br>
@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger">
        <ul>
            @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
            {
                <li>@error.ErrorMessage</li>
            }
        </ul>
        <br>
    </div>
}

DirectoryStructureApp.Web/Views/Directories/Index.cshtml
@{
    ViewData["Title"] = "Directory Structure App";
}

<h2>Choose your action</h2>

<a href="@Url.Action("View", "Directories")" class="btn btn-primary">See directories</a>
<a href="@Url.Action("Import", "Directories")" class="btn btn-secondary">Import directories from file system</a>

DirectoryStructureApp.Web/Views/Directories/View.cshtml
@using DirectoryStructureApp.BLL.DTOs;
@model List<DirectoryDto>
@{
    ViewData["Title"] = "Directory Structure";
}

@foreach(var parentDirectory in Model)
{
    <h4>
        Folder: @parentDirectory.Name
        <a asp-controller="Directories" asp-action="ConfirmDelete" asp-route-directoryId="@parentDirectory.Id" class="btn btn-danger btn-sm">Delete</a>
    </h4>
    foreach (var subDirectory in parentDirectory.SubDirectories)
    {
        <a asp-controller="Directories" asp-action="View" asp-route-directoryId="@subDirectory.Id">@subDirectory.Name</a>
        <br>
    }
    <br>
}

<form asp-controller="Directories" asp-action="ExportFile" method="post">
    @if (Model.Count == 1)
    {
        <input type="hidden" name="directoryId" value="@Model.First().Id" />
    }
    <button type="submit" class="btn btn-primary">Export to file</button>
</form>

DirectoryStructureApp.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DirectoryStructureApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Directories" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Directories" asp-action="View">Directories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Directories" asp-action="Import">Import</a>
                    </li>
                </ul>
            </div>
        </nav>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>